config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'help' => 'static_pages#help'
  get 'contacts' => 'static_pages#contacts'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Электронное письмо с инструкциями 
      по сбросу пароля отправлено на вашу электронную почту"
      redirect_to root_url
    else
      flash.now[:danger] = "Данный адрес электронной почты не найден"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "Не может быть пустым.")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Пароль был сброшен."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password,
                                 :password_confirmation)
  end

  # Предфильтры
  def get_user
    @user = User.find_by(email: params[:email])
  end

  # Подтверждает валидность пользователя.
  def valid_user
    unless (@user && @user.activated? &&
            @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # Проверяет срок действия reset-токена
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, 'Придумайте пароль' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Повторите пароль" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Изменить пароль", 
            class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Забыла пароль") %>
 
<div class="signup-login">
  <h1>Забыли пароль?</h1>
</div>

<div class="row">
  <div class="form_forgotPassword">
  	<%= form_for(:password_reset, 
                 url: password_resets_path) do |f| %>
  	  <div class="fiels_password_reset">
  	    <%= f.label :email, 'Введите ваш email' %><br />
  	    <%= f.email_field :email, :class => 'form_control2' %>
      </div>
      <div class="butnForgot">
  	    <%= f.submit "Отправить", :class => 'btnForgot' %>
  	  </div>
  	<% end %>              
  </div>
</div>