config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'help' => 'static_pages#help'
  get 'contacts' => 'static_pages#contacts'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Мотивашка</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar navbar-fixed-top">
    <div class="container">
      <div class='logo'>Motivashka</div>
      <nav>
        <ul class="topmenu">
          <li><%= link_to 'Главная', root_path,
                               :class => "a" %></li>
          <% if logged_in? %>
            <li><%= link_to 'Мотивашки', users_path,
                               :class => "a" %></li>

            <li><%= link_to 'Профиль', current_user, 
                               :class => 'a' %>
            <ul class="submenu">
              <li><%= link_to 'Настройки', 
                      edit_user_path(current_user),
                               :class => "a" %></li>
              <li><%= link_to 'Выход', logout_path,
                               method: "delete" %></li>
            </ul>
            </li>

          <li><%= link_to 'Помощь', help_path,
                               :class => "a" %></li>
          <% else %>
            <li><%= link_to 'Войти', login_path, 
                               :class => "a" %></li>
          <% end %>

        <li><%= link_to 'Контакты', contacts_path,
                               :class => "a" %></li>
        </ul>
      </nav>        
    </div>
  </header>

  <div class='container'> 
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
    <% end %>     
    <%= yield %>
  </div> 

</body>
</html>